services:
  cv-site:
    build: .
    container_name: cv_portfolio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Memetakan folder SSL dari VPS ke dalam kontainer Docker
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
