    server {
    listen 80;
    server_name andresaputra.trihaka.my.id;
    
    # Pengalihan otomatis dari HTTP ke HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name andresaputra.trihaka.my.id;

    # Jalur sertifikat SSL di dalam kontainer
    ssl_certificate /etc/letsencrypt/live/andresaputra.trihaka.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/andresaputra.trihaka.my.id/privkey.pem;

    # Optimasi Keamanan SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
